package ogame

type PlanetEmpire struct {
	Groups struct {
		Defence   []int    `json:"defence"`
		Items     []string `json:"items"`
		Research  []int    `json:"research"`
		Resources []string `json:"resources"`
		Ships     []int    `json:"ships"`
		Station   []int    `json:"station"`
		Storage   []string `json:"storage"`
		Supply    []int    `json:"supply"`
	} `json:"groups"`
	Planets []struct {
		Num1       int    `json:"1"`
		Num2       int    `json:"2"`
		Num3       int    `json:"3"`
		Num4       int    `json:"4"`
		Num12      int    `json:"12"`
		Num14      int    `json:"14"`
		Num15      int    `json:"15"`
		Num21      int    `json:"21"`
		Num22      int    `json:"22"`
		Num23      int    `json:"23"`
		Num24      int    `json:"24"`
		Num31      int    `json:"31"`
		Num33      int    `json:"33"`
		Num34      int    `json:"34"`
		Num36      int    `json:"36"`
		Num44      int    `json:"44"`
		Num106     int    `json:"106"`
		Num108     int    `json:"108"`
		Num109     int    `json:"109"`
		Num110     int    `json:"110"`
		Num111     int    `json:"111"`
		Num113     int    `json:"113"`
		Num114     int    `json:"114"`
		Num115     int    `json:"115"`
		Num117     int    `json:"117"`
		Num118     int    `json:"118"`
		Num120     int    `json:"120"`
		Num121     int    `json:"121"`
		Num122     int    `json:"122"`
		Num123     int    `json:"123"`
		Num124     int    `json:"124"`
		Num199     int    `json:"199"`
		Num202     string `json:"202"`
		Num203     int    `json:"203"`
		Num204     string `json:"204"`
		Num205     int    `json:"205"`
		Num206     string `json:"206"`
		Num207     int    `json:"207"`
		Num208     string `json:"208"`
		Num209     string `json:"209"`
		Num210     string `json:"210"`
		Num211     string `json:"211"`
		Num212     int    `json:"212"`
		Num213     string `json:"213"`
		Num214     string `json:"214"`
		Num215     int    `json:"215"`
		Num217     int    `json:"217"`
		Num218     string `json:"218"`
		Num219     string `json:"219"`
		Num401     int    `json:"401"`
		Num402     int    `json:"402"`
		Num403     int    `json:"403"`
		Num404     int    `json:"404"`
		Num405     int    `json:"405"`
		Num406     int    `json:"406"`
		Num407     int    `json:"407"`
		Num408     int    `json:"408"`
		Num502     int    `json:"502"`
		Num503     string `json:"503"`
		One06HTML  string `json:"106_html"`
		One08HTML  string `json:"108_html"`
		One09HTML  string `json:"109_html"`
		One10HTML  string `json:"110_html"`
		One11HTML  string `json:"111_html"`
		One13HTML  string `json:"113_html"`
		One14HTML  string `json:"114_html"`
		One15HTML  string `json:"115_html"`
		One17HTML  string `json:"117_html"`
		One18HTML  string `json:"118_html"`
		One20HTML  string `json:"120_html"`
		One21HTML  string `json:"121_html"`
		One22HTML  string `json:"122_html"`
		One23HTML  string `json:"123_html"`
		One24HTML  string `json:"124_html"`
		One2HTML   string `json:"12_html"`
		One4HTML   string `json:"14_html"`
		One5HTML   string `json:"15_html"`
		One99HTML  string `json:"199_html"`
		OneHTML    string `json:"1_html"`
		Two02HTML  string `json:"202_html"`
		Two03HTML  string `json:"203_html"`
		Two04HTML  string `json:"204_html"`
		Two05HTML  string `json:"205_html"`
		Two06HTML  string `json:"206_html"`
		Two07HTML  string `json:"207_html"`
		Two08HTML  string `json:"208_html"`
		Two09HTML  string `json:"209_html"`
		Two10HTML  string `json:"210_html"`
		Two11HTML  string `json:"211_html"`
		Two12HTML  string `json:"212_html"`
		Two13HTML  string `json:"213_html"`
		Two14HTML  string `json:"214_html"`
		Two15HTML  string `json:"215_html"`
		Two17HTML  string `json:"217_html"`
		Two18HTML  string `json:"218_html"`
		Two19HTML  string `json:"219_html"`
		Two1HTML   string `json:"21_html"`
		Two2HTML   string `json:"22_html"`
		Two3HTML   string `json:"23_html"`
		Two4HTML   string `json:"24_html"`
		TwoHTML    string `json:"2_html"`
		Three1HTML string `json:"31_html"`
		Three3HTML string `json:"33_html"`
		Three4HTML string `json:"34_html"`
		Three6HTML string `json:"36_html"`
		ThreeHTML  string `json:"3_html"`
		Four01HTML string `json:"401_html"`
		Four02HTML string `json:"402_html"`
		Four03HTML string `json:"403_html"`
		Four04HTML string `json:"404_html"`
		Four05HTML string `json:"405_html"`
		Four06HTML string `json:"406_html"`
		Four07HTML string `json:"407_html"`
		Four08HTML string `json:"408_html"`
		Four4HTML  string `json:"44_html"`
		FourHTML   string `json:"4_html"`
		Five02HTML string `json:"502_html"`
		Five03HTML string `json:"503_html"`
		Border     string `json:"border"`
		Cached     struct {
			Galaxy                string      `json:"galaxy"`
			ID                    string      `json:"id"`
			IDOfSibling           interface{} `json:"idOfSibling"`
			MaxFields             int         `json:"maxFields"`
			MoveCoolDownTimestamp string      `json:"moveCoolDownTimestamp"`
			MoveInProgress        string      `json:"moveInProgress"`
			Name                  string      `json:"name"`
			Position              string      `json:"position"`
			Size                  string      `json:"size"`
			System                string      `json:"system"`
			Temperature           string      `json:"temperature"`
			Type                  string      `json:"type"`
			UsedFields            int         `json:"usedFields"`
		} `json:"cached"`
		Coordinates          string      `json:"coordinates"`
		CoordinatesLink      string      `json:"coordinatesLink"`
		Crystal              int         `json:"crystal"`
		CrystalHide          int         `json:"crystalHide"`
		CrystalHideHTML      string      `json:"crystalHide_html"`
		CrystalStorage       int         `json:"crystalStorage"`
		CrystalStorageHTML   string      `json:"crystalStorage_html"`
		CrystalHTML          string      `json:"crystal_html"`
		DbPar1               string      `json:"db_par1"`
		DbPar2               string      `json:"db_par2"`
		Deuterium            int         `json:"deuterium"`
		DeuteriumHide        int         `json:"deuteriumHide"`
		DeuteriumHideHTML    string      `json:"deuteriumHide_html"`
		DeuteriumStorage     int         `json:"deuteriumStorage"`
		DeuteriumStorageHTML string      `json:"deuteriumStorage_html"`
		DeuteriumHTML        string      `json:"deuterium_html"`
		Diameter             string      `json:"diameter"`
		DiameterDescr        string      `json:"diameterDescr"`
		DiameterTooltip      string      `json:"diameterTooltip"`
		Energy               string      `json:"energy"`
		EnergyDescr          string      `json:"energyDescr"`
		EnergyTooltip        string      `json:"energyTooltip"`
		EquipmentHTML        string      `json:"equipment_html"`
		FieldMax             string      `json:"fieldMax"`
		FieldUsed            string      `json:"fieldUsed"`
		Galaxy               string      `json:"galaxy"`
		ID                   string      `json:"id"`
		Image                string      `json:"image"`
		Metal                int         `json:"metal"`
		MetalHide            int         `json:"metalHide"`
		MetalHideHTML        string      `json:"metalHide_html"`
		MetalStorage         int         `json:"metalStorage"`
		MetalStorageHTML     string      `json:"metalStorage_html"`
		MetalHTML            string      `json:"metal_html"`
		MoonID               interface{} `json:"moonID"`
		MoveCooldownTime     string      `json:"moveCooldownTime"`
		MoveInProgress       string      `json:"moveInProgress"`
		Name                 string      `json:"name"`
		Position             string      `json:"position"`
		Production           struct {
			Daily           []int `json:"daily"`
			GeneralIncoming []int `json:"generalIncoming"`
			Hourly          []int `json:"hourly"`
			Production      struct {
				Num1 struct {
					Num0        int         `json:"0"`
					Num1        int         `json:"1"`
					Num2        int         `json:"2"`
					Num3        int         `json:"3"`
					Num5        int         `json:"5"`
					Num6        int         `json:"6"`
					Num7        int         `json:"7"`
					Num8        int         `json:"8"`
					Active      bool        `json:"active"`
					Image       interface{} `json:"image"`
					IsOfficer   bool        `json:"isOfficer"`
					Link        interface{} `json:"link"`
					Number      int         `json:"number"`
					NumberCat   string      `json:"number_cat"`
					ShowNumber  bool        `json:"showNumber"`
					ShowPercent bool        `json:"showPercent"`
					Tooltip     interface{} `json:"tooltip"`
				} `json:"1"`
				Num2 struct {
					Num0        int         `json:"0"`
					Num1        int         `json:"1"`
					Num2        int         `json:"2"`
					Num3        int         `json:"3"`
					Num5        int         `json:"5"`
					Num6        int         `json:"6"`
					Num7        int         `json:"7"`
					Num8        int         `json:"8"`
					Active      bool        `json:"active"`
					Image       interface{} `json:"image"`
					IsOfficer   bool        `json:"isOfficer"`
					Link        interface{} `json:"link"`
					Number      int         `json:"number"`
					NumberCat   string      `json:"number_cat"`
					ShowNumber  bool        `json:"showNumber"`
					ShowPercent bool        `json:"showPercent"`
					Tooltip     interface{} `json:"tooltip"`
				} `json:"2"`
				Num3 struct {
					Num0        int         `json:"0"`
					Num1        int         `json:"1"`
					Num2        int         `json:"2"`
					Num3        int         `json:"3"`
					Num5        int         `json:"5"`
					Num6        int         `json:"6"`
					Num7        int         `json:"7"`
					Num8        int         `json:"8"`
					Active      bool        `json:"active"`
					Image       interface{} `json:"image"`
					IsOfficer   bool        `json:"isOfficer"`
					Link        interface{} `json:"link"`
					Number      int         `json:"number"`
					NumberCat   string      `json:"number_cat"`
					ShowNumber  bool        `json:"showNumber"`
					ShowPercent bool        `json:"showPercent"`
					Tooltip     interface{} `json:"tooltip"`
				} `json:"3"`
				Num4 struct {
					Num0        int         `json:"0"`
					Num1        int         `json:"1"`
					Num2        int         `json:"2"`
					Num3        int         `json:"3"`
					Num5        int         `json:"5"`
					Num6        int         `json:"6"`
					Num7        int         `json:"7"`
					Num8        int         `json:"8"`
					Active      bool        `json:"active"`
					Image       interface{} `json:"image"`
					IsOfficer   bool        `json:"isOfficer"`
					Link        interface{} `json:"link"`
					Number      int         `json:"number"`
					NumberCat   string      `json:"number_cat"`
					ShowNumber  bool        `json:"showNumber"`
					ShowPercent bool        `json:"showPercent"`
					Tooltip     interface{} `json:"tooltip"`
				} `json:"4"`
				Num12 struct {
					Num0        int         `json:"0"`
					Num1        int         `json:"1"`
					Num2        int         `json:"2"`
					Num3        int         `json:"3"`
					Num5        int         `json:"5"`
					Num6        int         `json:"6"`
					Num7        int         `json:"7"`
					Num8        int         `json:"8"`
					Active      bool        `json:"active"`
					Image       interface{} `json:"image"`
					IsOfficer   bool        `json:"isOfficer"`
					Link        interface{} `json:"link"`
					Number      int         `json:"number"`
					NumberCat   string      `json:"number_cat"`
					ShowNumber  bool        `json:"showNumber"`
					ShowPercent bool        `json:"showPercent"`
					Tooltip     interface{} `json:"tooltip"`
				} `json:"12"`
				Num122 struct {
					Num0        int         `json:"0"`
					Num1        int         `json:"1"`
					Num2        int         `json:"2"`
					Num3        int         `json:"3"`
					Num5        int         `json:"5"`
					Num6        int         `json:"6"`
					Num7        int         `json:"7"`
					Num8        int         `json:"8"`
					Active      bool        `json:"active"`
					Image       interface{} `json:"image"`
					IsOfficer   bool        `json:"isOfficer"`
					Link        interface{} `json:"link"`
					Number      int         `json:"number"`
					NumberCat   string      `json:"number_cat"`
					ShowNumber  bool        `json:"showNumber"`
					ShowPercent bool        `json:"showPercent"`
					Tooltip     interface{} `json:"tooltip"`
				} `json:"122"`
				Num212 struct {
					Num0        int         `json:"0"`
					Num1        int         `json:"1"`
					Num2        int         `json:"2"`
					Num3        int         `json:"3"`
					Num5        int         `json:"5"`
					Num6        int         `json:"6"`
					Num7        int         `json:"7"`
					Num8        int         `json:"8"`
					Active      bool        `json:"active"`
					Image       interface{} `json:"image"`
					IsOfficer   bool        `json:"isOfficer"`
					Link        interface{} `json:"link"`
					Number      int         `json:"number"`
					NumberCat   string      `json:"number_cat"`
					ShowNumber  bool        `json:"showNumber"`
					ShowPercent bool        `json:"showPercent"`
					Tooltip     interface{} `json:"tooltip"`
				} `json:"212"`
				Num217 struct {
					Num0        int         `json:"0"`
					Num1        int         `json:"1"`
					Num2        int         `json:"2"`
					Num3        int         `json:"3"`
					Num5        int         `json:"5"`
					Num6        int         `json:"6"`
					Num7        int         `json:"7"`
					Num8        int         `json:"8"`
					Active      bool        `json:"active"`
					Image       interface{} `json:"image"`
					IsOfficer   bool        `json:"isOfficer"`
					Link        interface{} `json:"link"`
					Number      int         `json:"number"`
					NumberCat   string      `json:"number_cat"`
					ShowNumber  bool        `json:"showNumber"`
					ShowPercent bool        `json:"showPercent"`
					Tooltip     interface{} `json:"tooltip"`
				} `json:"217"`
				Num1000 struct {
					Num0        int         `json:"0"`
					Num1        int         `json:"1"`
					Num2        int         `json:"2"`
					Num3        int         `json:"3"`
					Num5        int         `json:"5"`
					Num6        int         `json:"6"`
					Num7        int         `json:"7"`
					Num8        int         `json:"8"`
					Active      bool        `json:"active"`
					Image       interface{} `json:"image"`
					IsOfficer   bool        `json:"isOfficer"`
					Link        interface{} `json:"link"`
					Number      int         `json:"number"`
					ShowNumber  bool        `json:"showNumber"`
					ShowPercent bool        `json:"showPercent"`
					Tooltip     interface{} `json:"tooltip"`
				} `json:"1000"`
				Num1001 struct {
					Num0         int    `json:"0"`
					Num1         int    `json:"1"`
					Num2         int    `json:"2"`
					Num3         int    `json:"3"`
					Num5         int    `json:"5"`
					Num6         int    `json:"6"`
					Num7         int    `json:"7"`
					Num8         int    `json:"8"`
					Active       bool   `json:"active"`
					Image        string `json:"image"`
					IsOfficer    bool   `json:"isOfficer"`
					Link         string `json:"link"`
					Number       int    `json:"number"`
					ShowNumber   bool   `json:"showNumber"`
					ShowPercent  bool   `json:"showPercent"`
					Tooltip      string `json:"tooltip"`
					TooltipShort string `json:"tooltipShort"`
				} `json:"1001"`
				Num1002 struct {
					Num0         int    `json:"0"`
					Num1         int    `json:"1"`
					Num2         int    `json:"2"`
					Num3         int    `json:"3"`
					Num5         int    `json:"5"`
					Num6         int    `json:"6"`
					Num7         int    `json:"7"`
					Num8         int    `json:"8"`
					Active       bool   `json:"active"`
					Image        string `json:"image"`
					IsOfficer    bool   `json:"isOfficer"`
					Link         string `json:"link"`
					Number       int    `json:"number"`
					ShowNumber   bool   `json:"showNumber"`
					ShowPercent  bool   `json:"showPercent"`
					Tooltip      string `json:"tooltip"`
					TooltipShort string `json:"tooltipShort"`
				} `json:"1002"`
				Num1003 struct {
					Num0         int    `json:"0"`
					Num1         int    `json:"1"`
					Num2         int    `json:"2"`
					Num3         int    `json:"3"`
					Num5         int    `json:"5"`
					Num6         int    `json:"6"`
					Num7         int    `json:"7"`
					Num8         int    `json:"8"`
					Active       bool   `json:"active"`
					Image        string `json:"image"`
					IsOfficer    bool   `json:"isOfficer"`
					Link         string `json:"link"`
					Number       int    `json:"number"`
					ShowNumber   bool   `json:"showNumber"`
					ShowPercent  bool   `json:"showPercent"`
					Tooltip      string `json:"tooltip"`
					TooltipShort string `json:"tooltipShort"`
				} `json:"1003"`
				Num1004 struct {
					Num0         int         `json:"0"`
					Num1         int         `json:"1"`
					Num2         int         `json:"2"`
					Num3         int         `json:"3"`
					Num5         int         `json:"5"`
					Num6         int         `json:"6"`
					Num7         int         `json:"7"`
					Num8         int         `json:"8"`
					Active       bool        `json:"active"`
					Image        string      `json:"image"`
					IsOfficer    bool        `json:"isOfficer"`
					Link         interface{} `json:"link"`
					Name         string      `json:"name"`
					Number       int         `json:"number"`
					ShowNumber   bool        `json:"showNumber"`
					ShowPercent  bool        `json:"showPercent"`
					Tooltip      string      `json:"tooltip"`
					TooltipShort string      `json:"tooltipShort"`
				} `json:"1004"`
			} `json:"production"`
			ProductionFactor int       `json:"productionFactor"`
			Resources        []float64 `json:"resources"`
			Storage          []int     `json:"storage"`
			TechList         []int     `json:"techList"`
			Weekly           []int     `json:"weekly"`
		} `json:"production"`
		System      string `json:"system"`
		Temperature string `json:"temperature"`
		Type        string `json:"type"`
	} `json:"planets"`
	Translations struct {
		Groups struct {
			Defence   string `json:"defence"`
			Items     string `json:"items"`
			Research  string `json:"research"`
			Resources string `json:"resources"`
			Ships     string `json:"ships"`
			Station   string `json:"station"`
			Storage   string `json:"storage"`
			Supply    string `json:"supply"`
		} `json:"groups"`
		Header    string `json:"header"`
		MoonsTab  string `json:"moonsTab"`
		NoSummary string `json:"noSummary"`
		Planets   struct {
			Num1                 string `json:"1"`
			Num2                 string `json:"2"`
			Num3                 string `json:"3"`
			Num4                 string `json:"4"`
			Num12                string `json:"12"`
			Num14                string `json:"14"`
			Num15                string `json:"15"`
			Num21                string `json:"21"`
			Num22                string `json:"22"`
			Num23                string `json:"23"`
			Num24                string `json:"24"`
			Num31                string `json:"31"`
			Num33                string `json:"33"`
			Num34                string `json:"34"`
			Num36                string `json:"36"`
			Num44                string `json:"44"`
			Num106               string `json:"106"`
			Num108               string `json:"108"`
			Num109               string `json:"109"`
			Num110               string `json:"110"`
			Num111               string `json:"111"`
			Num113               string `json:"113"`
			Num114               string `json:"114"`
			Num115               string `json:"115"`
			Num117               string `json:"117"`
			Num118               string `json:"118"`
			Num120               string `json:"120"`
			Num121               string `json:"121"`
			Num122               string `json:"122"`
			Num123               string `json:"123"`
			Num124               string `json:"124"`
			Num199               string `json:"199"`
			Num202               string `json:"202"`
			Num203               string `json:"203"`
			Num204               string `json:"204"`
			Num205               string `json:"205"`
			Num206               string `json:"206"`
			Num207               string `json:"207"`
			Num208               string `json:"208"`
			Num209               string `json:"209"`
			Num210               string `json:"210"`
			Num211               string `json:"211"`
			Num212               string `json:"212"`
			Num213               string `json:"213"`
			Num214               string `json:"214"`
			Num215               string `json:"215"`
			Num217               string `json:"217"`
			Num218               string `json:"218"`
			Num219               string `json:"219"`
			Num401               string `json:"401"`
			Num402               string `json:"402"`
			Num403               string `json:"403"`
			Num404               string `json:"404"`
			Num405               string `json:"405"`
			Num406               string `json:"406"`
			Num407               string `json:"407"`
			Num408               string `json:"408"`
			Num502               string `json:"502"`
			Num503               string `json:"503"`
			One06Full            string `json:"106_full"`
			One08Full            string `json:"108_full"`
			One09Full            string `json:"109_full"`
			One10Full            string `json:"110_full"`
			One11Full            string `json:"111_full"`
			One13Full            string `json:"113_full"`
			One14Full            string `json:"114_full"`
			One15Full            string `json:"115_full"`
			One17Full            string `json:"117_full"`
			One18Full            string `json:"118_full"`
			One20Full            string `json:"120_full"`
			One21Full            string `json:"121_full"`
			One22Full            string `json:"122_full"`
			One23Full            string `json:"123_full"`
			One24Full            string `json:"124_full"`
			One2Full             string `json:"12_full"`
			One4Full             string `json:"14_full"`
			One5Full             string `json:"15_full"`
			One99Full            string `json:"199_full"`
			OneFull              string `json:"1_full"`
			Two02Full            string `json:"202_full"`
			Two03Full            string `json:"203_full"`
			Two04Full            string `json:"204_full"`
			Two05Full            string `json:"205_full"`
			Two06Full            string `json:"206_full"`
			Two07Full            string `json:"207_full"`
			Two08Full            string `json:"208_full"`
			Two09Full            string `json:"209_full"`
			Two10Full            string `json:"210_full"`
			Two11Full            string `json:"211_full"`
			Two12Full            string `json:"212_full"`
			Two13Full            string `json:"213_full"`
			Two14Full            string `json:"214_full"`
			Two15Full            string `json:"215_full"`
			Two17Full            string `json:"217_full"`
			Two18Full            string `json:"218_full"`
			Two19Full            string `json:"219_full"`
			Two1Full             string `json:"21_full"`
			Two2Full             string `json:"22_full"`
			Two3Full             string `json:"23_full"`
			Two4Full             string `json:"24_full"`
			TwoFull              string `json:"2_full"`
			Three1Full           string `json:"31_full"`
			Three3Full           string `json:"33_full"`
			Three4Full           string `json:"34_full"`
			Three6Full           string `json:"36_full"`
			ThreeFull            string `json:"3_full"`
			Four01Full           string `json:"401_full"`
			Four02Full           string `json:"402_full"`
			Four03Full           string `json:"403_full"`
			Four04Full           string `json:"404_full"`
			Four05Full           string `json:"405_full"`
			Four06Full           string `json:"406_full"`
			Four07Full           string `json:"407_full"`
			Four08Full           string `json:"408_full"`
			Four4Full            string `json:"44_full"`
			FourFull             string `json:"4_full"`
			Five02Full           string `json:"502_full"`
			Five03Full           string `json:"503_full"`
			Crystal              string `json:"crystal"`
			CrystalStorage       string `json:"crystalStorage"`
			CrystalStorageFull   string `json:"crystalStorage_full"`
			CrystalFull          string `json:"crystal_full"`
			Deuterium            string `json:"deuterium"`
			DeuteriumStorage     string `json:"deuteriumStorage"`
			DeuteriumStorageFull string `json:"deuteriumStorage_full"`
			DeuteriumFull        string `json:"deuterium_full"`
			Energy               string `json:"energy"`
			EnergyFull           string `json:"energy_full"`
			Equipment            string `json:"equipment"`
			EquipmentFull        string `json:"equipment_full"`
			Fusion               string `json:"fusion"`
			FusionFull           string `json:"fusion_full"`
			Metal                string `json:"metal"`
			MetalStorage         string `json:"metalStorage"`
			MetalStorageFull     string `json:"metalStorage_full"`
			MetalFull            string `json:"metal_full"`
			Satellite            string `json:"satellite"`
			SatelliteFull        string `json:"satellite_full"`
			Solar                string `json:"solar"`
			SolarFull            string `json:"solar_full"`
		} `json:"planets"`
		PlanetsTab string `json:"planetsTab"`
		Production struct {
			Daily  string `json:"daily"`
			Hourly string `json:"hourly"`
			Weekly string `json:"weekly"`
		} `json:"production"`
		Reset   string `json:"reset"`
		Summary string `json:"summary"`
	} `json:"translations"`
}

type MoonEmpire struct {
	Groups struct {
		Defence   []int    `json:"defence"`
		Items     []string `json:"items"`
		Research  []int    `json:"research"`
		Resources []string `json:"resources"`
		Ships     []int    `json:"ships"`
		Station   []int    `json:"station"`
		Storage   []string `json:"storage"`
		Supply    []int    `json:"supply"`
	} `json:"groups"`
	Planets []struct {
		Num14      int    `json:"14"`
		Num21      int    `json:"21"`
		Num22      string `json:"22"`
		Num23      string `json:"23"`
		Num24      string `json:"24"`
		Num41      int    `json:"41"`
		Num42      int    `json:"42"`
		Num43      int    `json:"43"`
		Num106     int    `json:"106"`
		Num108     int    `json:"108"`
		Num109     int    `json:"109"`
		Num110     int    `json:"110"`
		Num111     int    `json:"111"`
		Num113     int    `json:"113"`
		Num114     int    `json:"114"`
		Num115     int    `json:"115"`
		Num117     int    `json:"117"`
		Num118     int    `json:"118"`
		Num120     int    `json:"120"`
		Num121     int    `json:"121"`
		Num122     int    `json:"122"`
		Num123     int    `json:"123"`
		Num124     int    `json:"124"`
		Num199     int    `json:"199"`
		Num202     string `json:"202"`
		Num203     int    `json:"203"`
		Num204     string `json:"204"`
		Num205     string `json:"205"`
		Num206     string `json:"206"`
		Num207     string `json:"207"`
		Num208     int    `json:"208"`
		Num209     int    `json:"209"`
		Num210     int    `json:"210"`
		Num211     string `json:"211"`
		Num212     string `json:"212"`
		Num213     string `json:"213"`
		Num214     int    `json:"214"`
		Num215     string `json:"215"`
		Num217     string `json:"217"`
		Num218     string `json:"218"`
		Num219     string `json:"219"`
		Num401     int    `json:"401"`
		Num402     int    `json:"402"`
		Num403     int    `json:"403"`
		Num404     string `json:"404"`
		Num405     string `json:"405"`
		Num406     int    `json:"406"`
		Num407     int    `json:"407"`
		Num408     int    `json:"408"`
		Num502     string `json:"502"`
		Num503     string `json:"503"`
		One06HTML  string `json:"106_html"`
		One08HTML  string `json:"108_html"`
		One09HTML  string `json:"109_html"`
		One10HTML  string `json:"110_html"`
		One11HTML  string `json:"111_html"`
		One13HTML  string `json:"113_html"`
		One14HTML  string `json:"114_html"`
		One15HTML  string `json:"115_html"`
		One17HTML  string `json:"117_html"`
		One18HTML  string `json:"118_html"`
		One20HTML  string `json:"120_html"`
		One21HTML  string `json:"121_html"`
		One22HTML  string `json:"122_html"`
		One23HTML  string `json:"123_html"`
		One24HTML  string `json:"124_html"`
		One4HTML   string `json:"14_html"`
		One99HTML  string `json:"199_html"`
		Two02HTML  string `json:"202_html"`
		Two03HTML  string `json:"203_html"`
		Two04HTML  string `json:"204_html"`
		Two05HTML  string `json:"205_html"`
		Two06HTML  string `json:"206_html"`
		Two07HTML  string `json:"207_html"`
		Two08HTML  string `json:"208_html"`
		Two09HTML  string `json:"209_html"`
		Two10HTML  string `json:"210_html"`
		Two11HTML  string `json:"211_html"`
		Two12HTML  string `json:"212_html"`
		Two13HTML  string `json:"213_html"`
		Two14HTML  string `json:"214_html"`
		Two15HTML  string `json:"215_html"`
		Two17HTML  string `json:"217_html"`
		Two18HTML  string `json:"218_html"`
		Two19HTML  string `json:"219_html"`
		Two1HTML   string `json:"21_html"`
		Two2HTML   string `json:"22_html"`
		Two3HTML   string `json:"23_html"`
		Two4HTML   string `json:"24_html"`
		Four01HTML string `json:"401_html"`
		Four02HTML string `json:"402_html"`
		Four03HTML string `json:"403_html"`
		Four04HTML string `json:"404_html"`
		Four05HTML string `json:"405_html"`
		Four06HTML string `json:"406_html"`
		Four07HTML string `json:"407_html"`
		Four08HTML string `json:"408_html"`
		Four1HTML  string `json:"41_html"`
		Four2HTML  string `json:"42_html"`
		Four3HTML  string `json:"43_html"`
		Five02HTML string `json:"502_html"`
		Five03HTML string `json:"503_html"`
		Border     string `json:"border"`
		Cached     struct {
			Galaxy                string `json:"galaxy"`
			ID                    string `json:"id"`
			IDOfSibling           string `json:"idOfSibling"`
			MaxFields             int    `json:"maxFields"`
			MoveCoolDownTimestamp string `json:"moveCoolDownTimestamp"`
			MoveInProgress        string `json:"moveInProgress"`
			Name                  string `json:"name"`
			Position              string `json:"position"`
			Size                  string `json:"size"`
			System                string `json:"system"`
			Temperature           string `json:"temperature"`
			Type                  string `json:"type"`
			UsedFields            int    `json:"usedFields"`
		} `json:"cached"`
		Coordinates          string `json:"coordinates"`
		CoordinatesLink      string `json:"coordinatesLink"`
		Crystal              int    `json:"crystal"`
		CrystalHide          int    `json:"crystalHide"`
		CrystalHideHTML      string `json:"crystalHide_html"`
		CrystalStorage       int    `json:"crystalStorage"`
		CrystalStorageHTML   string `json:"crystalStorage_html"`
		CrystalHTML          string `json:"crystal_html"`
		DbPar1               string `json:"db_par1"`
		DbPar2               string `json:"db_par2"`
		Deuterium            int    `json:"deuterium"`
		DeuteriumHide        int    `json:"deuteriumHide"`
		DeuteriumHideHTML    string `json:"deuteriumHide_html"`
		DeuteriumStorage     int    `json:"deuteriumStorage"`
		DeuteriumStorageHTML string `json:"deuteriumStorage_html"`
		DeuteriumHTML        string `json:"deuterium_html"`
		Diameter             string `json:"diameter"`
		DiameterDescr        string `json:"diameterDescr"`
		DiameterTooltip      string `json:"diameterTooltip"`
		Energy               string `json:"energy"`
		EnergyDescr          string `json:"energyDescr"`
		EnergyTooltip        string `json:"energyTooltip"`
		EquipmentHTML        string `json:"equipment_html"`
		FieldMax             string `json:"fieldMax"`
		FieldUsed            string `json:"fieldUsed"`
		Galaxy               string `json:"galaxy"`
		ID                   string `json:"id"`
		Image                string `json:"image"`
		Metal                int    `json:"metal"`
		MetalHide            int    `json:"metalHide"`
		MetalHideHTML        string `json:"metalHide_html"`
		MetalStorage         int    `json:"metalStorage"`
		MetalStorageHTML     string `json:"metalStorage_html"`
		MetalHTML            string `json:"metal_html"`
		MoveCooldownTime     string `json:"moveCooldownTime"`
		MoveInProgress       string `json:"moveInProgress"`
		Name                 string `json:"name"`
		PlanetID             string `json:"planetID"`
		Position             string `json:"position"`
		Production           struct {
			Daily           []int `json:"daily"`
			GeneralIncoming []int `json:"generalIncoming"`
			Hourly          []int `json:"hourly"`
			Production      struct {
				Num1 struct {
					Num0        int         `json:"0"`
					Num1        int         `json:"1"`
					Num2        int         `json:"2"`
					Num3        int         `json:"3"`
					Num5        int         `json:"5"`
					Num6        int         `json:"6"`
					Num7        int         `json:"7"`
					Num8        int         `json:"8"`
					Active      bool        `json:"active"`
					Image       interface{} `json:"image"`
					IsOfficer   bool        `json:"isOfficer"`
					Link        interface{} `json:"link"`
					Number      int         `json:"number"`
					NumberCat   string      `json:"number_cat"`
					ShowNumber  bool        `json:"showNumber"`
					ShowPercent bool        `json:"showPercent"`
					Tooltip     interface{} `json:"tooltip"`
				} `json:"1"`
				Num2 struct {
					Num0        int         `json:"0"`
					Num1        int         `json:"1"`
					Num2        int         `json:"2"`
					Num3        int         `json:"3"`
					Num5        int         `json:"5"`
					Num6        int         `json:"6"`
					Num7        int         `json:"7"`
					Num8        int         `json:"8"`
					Active      bool        `json:"active"`
					Image       interface{} `json:"image"`
					IsOfficer   bool        `json:"isOfficer"`
					Link        interface{} `json:"link"`
					Number      int         `json:"number"`
					NumberCat   string      `json:"number_cat"`
					ShowNumber  bool        `json:"showNumber"`
					ShowPercent bool        `json:"showPercent"`
					Tooltip     interface{} `json:"tooltip"`
				} `json:"2"`
				Num3 struct {
					Num0        int         `json:"0"`
					Num1        int         `json:"1"`
					Num2        int         `json:"2"`
					Num3        int         `json:"3"`
					Num5        int         `json:"5"`
					Num6        int         `json:"6"`
					Num7        int         `json:"7"`
					Num8        int         `json:"8"`
					Active      bool        `json:"active"`
					Image       interface{} `json:"image"`
					IsOfficer   bool        `json:"isOfficer"`
					Link        interface{} `json:"link"`
					Number      int         `json:"number"`
					NumberCat   string      `json:"number_cat"`
					ShowNumber  bool        `json:"showNumber"`
					ShowPercent bool        `json:"showPercent"`
					Tooltip     interface{} `json:"tooltip"`
				} `json:"3"`
				Num4 struct {
					Num0        int         `json:"0"`
					Num1        int         `json:"1"`
					Num2        int         `json:"2"`
					Num3        int         `json:"3"`
					Num5        int         `json:"5"`
					Num6        int         `json:"6"`
					Num7        int         `json:"7"`
					Num8        int         `json:"8"`
					Active      bool        `json:"active"`
					Image       interface{} `json:"image"`
					IsOfficer   bool        `json:"isOfficer"`
					Link        interface{} `json:"link"`
					Number      int         `json:"number"`
					NumberCat   string      `json:"number_cat"`
					ShowNumber  bool        `json:"showNumber"`
					ShowPercent bool        `json:"showPercent"`
					Tooltip     interface{} `json:"tooltip"`
				} `json:"4"`
				Num12 struct {
					Num0        int         `json:"0"`
					Num1        int         `json:"1"`
					Num2        int         `json:"2"`
					Num3        int         `json:"3"`
					Num5        int         `json:"5"`
					Num6        int         `json:"6"`
					Num7        int         `json:"7"`
					Num8        int         `json:"8"`
					Active      bool        `json:"active"`
					Image       interface{} `json:"image"`
					IsOfficer   bool        `json:"isOfficer"`
					Link        interface{} `json:"link"`
					Number      int         `json:"number"`
					NumberCat   string      `json:"number_cat"`
					ShowNumber  bool        `json:"showNumber"`
					ShowPercent bool        `json:"showPercent"`
					Tooltip     interface{} `json:"tooltip"`
				} `json:"12"`
				Num122 struct {
					Num0        int         `json:"0"`
					Num1        int         `json:"1"`
					Num2        int         `json:"2"`
					Num3        int         `json:"3"`
					Num5        int         `json:"5"`
					Num6        int         `json:"6"`
					Num7        int         `json:"7"`
					Num8        int         `json:"8"`
					Active      bool        `json:"active"`
					Image       interface{} `json:"image"`
					IsOfficer   bool        `json:"isOfficer"`
					Link        interface{} `json:"link"`
					Number      int         `json:"number"`
					NumberCat   string      `json:"number_cat"`
					ShowNumber  bool        `json:"showNumber"`
					ShowPercent bool        `json:"showPercent"`
					Tooltip     interface{} `json:"tooltip"`
				} `json:"122"`
				Num212 struct {
					Num0        int         `json:"0"`
					Num1        int         `json:"1"`
					Num2        int         `json:"2"`
					Num3        int         `json:"3"`
					Num5        int         `json:"5"`
					Num6        int         `json:"6"`
					Num7        int         `json:"7"`
					Num8        int         `json:"8"`
					Active      bool        `json:"active"`
					Image       interface{} `json:"image"`
					IsOfficer   bool        `json:"isOfficer"`
					Link        interface{} `json:"link"`
					Number      int         `json:"number"`
					NumberCat   string      `json:"number_cat"`
					ShowNumber  bool        `json:"showNumber"`
					ShowPercent bool        `json:"showPercent"`
					Tooltip     interface{} `json:"tooltip"`
				} `json:"212"`
				Num217 struct {
					Num0        int         `json:"0"`
					Num1        int         `json:"1"`
					Num2        int         `json:"2"`
					Num3        int         `json:"3"`
					Num5        int         `json:"5"`
					Num6        int         `json:"6"`
					Num7        int         `json:"7"`
					Num8        int         `json:"8"`
					Active      bool        `json:"active"`
					Image       interface{} `json:"image"`
					IsOfficer   bool        `json:"isOfficer"`
					Link        interface{} `json:"link"`
					Number      int         `json:"number"`
					NumberCat   string      `json:"number_cat"`
					ShowNumber  bool        `json:"showNumber"`
					ShowPercent bool        `json:"showPercent"`
					Tooltip     interface{} `json:"tooltip"`
				} `json:"217"`
				Num1000 struct {
					Num0        int         `json:"0"`
					Num1        int         `json:"1"`
					Num2        int         `json:"2"`
					Num3        int         `json:"3"`
					Num5        int         `json:"5"`
					Num6        int         `json:"6"`
					Num7        int         `json:"7"`
					Num8        int         `json:"8"`
					Active      bool        `json:"active"`
					Image       interface{} `json:"image"`
					IsOfficer   bool        `json:"isOfficer"`
					Link        interface{} `json:"link"`
					Number      int         `json:"number"`
					ShowNumber  bool        `json:"showNumber"`
					ShowPercent bool        `json:"showPercent"`
					Tooltip     interface{} `json:"tooltip"`
				} `json:"1000"`
				Num1001 struct {
					Num0         int    `json:"0"`
					Num1         int    `json:"1"`
					Num2         int    `json:"2"`
					Num3         int    `json:"3"`
					Num5         int    `json:"5"`
					Num6         int    `json:"6"`
					Num7         int    `json:"7"`
					Num8         int    `json:"8"`
					Active       bool   `json:"active"`
					Image        string `json:"image"`
					IsOfficer    bool   `json:"isOfficer"`
					Link         string `json:"link"`
					Number       int    `json:"number"`
					ShowNumber   bool   `json:"showNumber"`
					ShowPercent  bool   `json:"showPercent"`
					Tooltip      string `json:"tooltip"`
					TooltipShort string `json:"tooltipShort"`
				} `json:"1001"`
				Num1002 struct {
					Num0         int    `json:"0"`
					Num1         int    `json:"1"`
					Num2         int    `json:"2"`
					Num3         int    `json:"3"`
					Num5         int    `json:"5"`
					Num6         int    `json:"6"`
					Num7         int    `json:"7"`
					Num8         int    `json:"8"`
					Active       bool   `json:"active"`
					Image        string `json:"image"`
					IsOfficer    bool   `json:"isOfficer"`
					Link         string `json:"link"`
					Number       int    `json:"number"`
					ShowNumber   bool   `json:"showNumber"`
					ShowPercent  bool   `json:"showPercent"`
					Tooltip      string `json:"tooltip"`
					TooltipShort string `json:"tooltipShort"`
				} `json:"1002"`
				Num1003 struct {
					Num0         int    `json:"0"`
					Num1         int    `json:"1"`
					Num2         int    `json:"2"`
					Num3         int    `json:"3"`
					Num5         int    `json:"5"`
					Num6         int    `json:"6"`
					Num7         int    `json:"7"`
					Num8         int    `json:"8"`
					Active       bool   `json:"active"`
					Image        string `json:"image"`
					IsOfficer    bool   `json:"isOfficer"`
					Link         string `json:"link"`
					Number       int    `json:"number"`
					ShowNumber   bool   `json:"showNumber"`
					ShowPercent  bool   `json:"showPercent"`
					Tooltip      string `json:"tooltip"`
					TooltipShort string `json:"tooltipShort"`
				} `json:"1003"`
				Num1004 struct {
					Num0         int         `json:"0"`
					Num1         int         `json:"1"`
					Num2         int         `json:"2"`
					Num3         int         `json:"3"`
					Num5         int         `json:"5"`
					Num6         int         `json:"6"`
					Num7         int         `json:"7"`
					Num8         int         `json:"8"`
					Active       bool        `json:"active"`
					Image        string      `json:"image"`
					IsOfficer    bool        `json:"isOfficer"`
					Link         interface{} `json:"link"`
					Name         string      `json:"name"`
					Number       int         `json:"number"`
					ShowNumber   bool        `json:"showNumber"`
					ShowPercent  bool        `json:"showPercent"`
					Tooltip      string      `json:"tooltip"`
					TooltipShort string      `json:"tooltipShort"`
				} `json:"1004"`
			} `json:"production"`
			ProductionFactor int   `json:"productionFactor"`
			Resources        []int `json:"resources"`
			Storage          []int `json:"storage"`
			TechList         []int `json:"techList"`
			Weekly           []int `json:"weekly"`
		} `json:"production"`
		System      string `json:"system"`
		Temperature string `json:"temperature"`
		Type        string `json:"type"`
	} `json:"planets"`
	Translations struct {
		Groups struct {
			Defence   string `json:"defence"`
			Items     string `json:"items"`
			Research  string `json:"research"`
			Resources string `json:"resources"`
			Ships     string `json:"ships"`
			Station   string `json:"station"`
			Storage   string `json:"storage"`
			Supply    string `json:"supply"`
		} `json:"groups"`
		Header    string `json:"header"`
		MoonsTab  string `json:"moonsTab"`
		NoSummary string `json:"noSummary"`
		Planets   struct {
			Num14                string `json:"14"`
			Num21                string `json:"21"`
			Num22                string `json:"22"`
			Num23                string `json:"23"`
			Num24                string `json:"24"`
			Num41                string `json:"41"`
			Num42                string `json:"42"`
			Num43                string `json:"43"`
			Num106               string `json:"106"`
			Num108               string `json:"108"`
			Num109               string `json:"109"`
			Num110               string `json:"110"`
			Num111               string `json:"111"`
			Num113               string `json:"113"`
			Num114               string `json:"114"`
			Num115               string `json:"115"`
			Num117               string `json:"117"`
			Num118               string `json:"118"`
			Num120               string `json:"120"`
			Num121               string `json:"121"`
			Num122               string `json:"122"`
			Num123               string `json:"123"`
			Num124               string `json:"124"`
			Num199               string `json:"199"`
			Num202               string `json:"202"`
			Num203               string `json:"203"`
			Num204               string `json:"204"`
			Num205               string `json:"205"`
			Num206               string `json:"206"`
			Num207               string `json:"207"`
			Num208               string `json:"208"`
			Num209               string `json:"209"`
			Num210               string `json:"210"`
			Num211               string `json:"211"`
			Num212               string `json:"212"`
			Num213               string `json:"213"`
			Num214               string `json:"214"`
			Num215               string `json:"215"`
			Num217               string `json:"217"`
			Num218               string `json:"218"`
			Num219               string `json:"219"`
			Num401               string `json:"401"`
			Num402               string `json:"402"`
			Num403               string `json:"403"`
			Num404               string `json:"404"`
			Num405               string `json:"405"`
			Num406               string `json:"406"`
			Num407               string `json:"407"`
			Num408               string `json:"408"`
			Num502               string `json:"502"`
			Num503               string `json:"503"`
			One06Full            string `json:"106_full"`
			One08Full            string `json:"108_full"`
			One09Full            string `json:"109_full"`
			One10Full            string `json:"110_full"`
			One11Full            string `json:"111_full"`
			One13Full            string `json:"113_full"`
			One14Full            string `json:"114_full"`
			One15Full            string `json:"115_full"`
			One17Full            string `json:"117_full"`
			One18Full            string `json:"118_full"`
			One20Full            string `json:"120_full"`
			One21Full            string `json:"121_full"`
			One22Full            string `json:"122_full"`
			One23Full            string `json:"123_full"`
			One24Full            string `json:"124_full"`
			One4Full             string `json:"14_full"`
			One99Full            string `json:"199_full"`
			Two02Full            string `json:"202_full"`
			Two03Full            string `json:"203_full"`
			Two04Full            string `json:"204_full"`
			Two05Full            string `json:"205_full"`
			Two06Full            string `json:"206_full"`
			Two07Full            string `json:"207_full"`
			Two08Full            string `json:"208_full"`
			Two09Full            string `json:"209_full"`
			Two10Full            string `json:"210_full"`
			Two11Full            string `json:"211_full"`
			Two12Full            string `json:"212_full"`
			Two13Full            string `json:"213_full"`
			Two14Full            string `json:"214_full"`
			Two15Full            string `json:"215_full"`
			Two17Full            string `json:"217_full"`
			Two18Full            string `json:"218_full"`
			Two19Full            string `json:"219_full"`
			Two1Full             string `json:"21_full"`
			Two2Full             string `json:"22_full"`
			Two3Full             string `json:"23_full"`
			Two4Full             string `json:"24_full"`
			Four01Full           string `json:"401_full"`
			Four02Full           string `json:"402_full"`
			Four03Full           string `json:"403_full"`
			Four04Full           string `json:"404_full"`
			Four05Full           string `json:"405_full"`
			Four06Full           string `json:"406_full"`
			Four07Full           string `json:"407_full"`
			Four08Full           string `json:"408_full"`
			Four1Full            string `json:"41_full"`
			Four2Full            string `json:"42_full"`
			Four3Full            string `json:"43_full"`
			Five02Full           string `json:"502_full"`
			Five03Full           string `json:"503_full"`
			Crystal              string `json:"crystal"`
			CrystalStorage       string `json:"crystalStorage"`
			CrystalStorageFull   string `json:"crystalStorage_full"`
			CrystalFull          string `json:"crystal_full"`
			Deuterium            string `json:"deuterium"`
			DeuteriumStorage     string `json:"deuteriumStorage"`
			DeuteriumStorageFull string `json:"deuteriumStorage_full"`
			DeuteriumFull        string `json:"deuterium_full"`
			Energy               string `json:"energy"`
			EnergyFull           string `json:"energy_full"`
			Equipment            string `json:"equipment"`
			EquipmentFull        string `json:"equipment_full"`
			Fusion               string `json:"fusion"`
			FusionFull           string `json:"fusion_full"`
			Metal                string `json:"metal"`
			MetalStorage         string `json:"metalStorage"`
			MetalStorageFull     string `json:"metalStorage_full"`
			MetalFull            string `json:"metal_full"`
			Satellite            string `json:"satellite"`
			SatelliteFull        string `json:"satellite_full"`
			Solar                string `json:"solar"`
			SolarFull            string `json:"solar_full"`
		} `json:"planets"`
		PlanetsTab string `json:"planetsTab"`
		Production struct {
			Daily  string `json:"daily"`
			Hourly string `json:"hourly"`
			Weekly string `json:"weekly"`
		} `json:"production"`
		Reset   string `json:"reset"`
		Summary string `json:"summary"`
	} `json:"translations"`
}
